[project]
name = "odoo-addons-oca-server-ux"
version = "18.0.20241025.0"
dependencies = [
    "odoo-addon-base_technical_features==18.0.*",
    "odoo-addon-developer_menu==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
